# This CI workflow runs fuzz test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: fuzz
jobs:
  fuzz:
    runs-on: ubuntu-latest
    name: ubuntu / nightly / ${{ matrix.fuzz-target }} / fuzz
    strategy:
      fail-fast: false
      matrix:
        fuzz-target: [fuzz_target_1]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@master
        with:
          components: llvm-tools-preview
          toolchain: nightly
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo install cargo-fuzz
      - run: cargo check
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo fuzz
        run: |
          ls *
          cd fuzz
          cargo +nightly fuzz run --release ${{ matrix.fuzz-target }} -- -max_total_time=300

      - name: Record Rust version
        run: echo "RUST=$(rustc --version)" >> "$GITHUB_ENV"
      # Upload fuzzing artifacts on failure for post-mortem debugging.
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fuzzing-artifacts-${{ matrix.fuzz_target }}-${{ github.sha }}
          path: fuzz/artifacts
